### PR TITLE
Add confirmation dialog before installing or uninstalling

### LINKED ISSUE #6: Add confirmation dialogs
Suggestion: when a user checks/unchecks a checkbox on the main page, show a confirmation diagram along the lines of ‘Are you sure you want to install/uninstall \<program version\>?’.

### PR DESCRIPTION
**Pull request by bradrn**
Fixes #6.

Some nasty subtleties here… in particular, digging through the `gi-gtk` source reveals that the `?self` implicit parameter gets disowned as soon as the callback returns. Thus, in the message box `respond` signal, properties must be set on the original `Gtk.Switch` object, rather than on the `?self` pointer of the outer callback (even though they should in theory be the same), since that pointer gets disowned before the message box signal can run.

Another point is that setting the activity programmatically also triggers the `stateSet` signal. Blocking this is more difficult than it should be, since it requires the handler ID, which can’t be accessed until after the message box has been created! It’s easier to just wrap the whole `mockInstall` function in a conditional, to ensure that the dialog isn’t shown twice.

### CODE REVIEW

**Comment by Kleidukos** [comment]
@bradrn this is interesting. Definitely would be worth it to write that down somewhere to help guide others.

**Comment by bradrn** [comment]
Yes, I definitely think it should be documented somewhere… but I’m not at all sure where. Maybe I’ll just open an issue on https://github.com/haskell-gi/haskell-gi.

(Also, do I need to worry about the failed CI?)

**Comment by Kleidukos** [comment]
> (Also, do I need to worry about the failed CI?)

This is where a nix setup would be useful… The runners are still running on an Ubuntu LTS that has an old version of libadwaita, if I'm not mistaken

**Comment by bradrn** [comment]
Further on `?self`… thanks to @garetxe \[ https://github.com/haskell-gi/haskell-gi/issues/408#issuecomment-1567522045 \], this issue is now fixed in `haskell-gi-0.26.5`. The freeze file pins us to `haskell-gi-0.26.4`, though, so probably it’s best to continue avoiding `?self` for now.

**Comment by Kleidukos** [comment]
@bradrn you can update the freeze file, it's better if we bump the version :+1: 

Regarding the CI I'll merge the PR despite of the runner.

**Pull request merged**
